#+title: Sway config
#+PROPERTY: header-args:sh :tangle "~/.config/i3/config"

* Variables
** Application
#+begin_src sh

set $mod Mod4
# Home row direction keys, like vim
set $left h
set $down j
set $up k
set $right l
# Your preferred terminal emulator
set $term alacritty
#+end_src
** IO
#+begin_src sh
#
# Example configuration:
#
#   output HDMI-A-1 resolution 1920x1080 position 1920,0
#
# Yofor_window [class="^.*"] border pixel 1u can get the names of your outputs by running: swaymsg -t get_outputs
for_window [class="^.*"] border none
#+end_src

* IO Configs
** Idle configuration
   exec swayidle -w \
          timeout 300 'swaylock -f -c 000000' \
          timeout 600 'swaymsg "output * dpms off"' resume 'swaymsg "output * dpms on"' \
          before-sleep 'swaylock -f -c 000000'

   This will lock your screen after 300 seconds of inactivity, then turn off
   your displays after another 300 seconds, and turn your screens back on when
   resumed. It will also lock your screen before your computer goes to sleep.

** Input configuration
 Example configuration:
#+begin_src sh
exec "setxkbmap -option 'grp:alt_shift_toggle' -layout us,ru,fr,ua"
#+end_src

* Key bindings
** Basics:
#+begin_src sh
# Start a terminal
bindsym $mod+Return exec $term
bindsym $mod+e exec emacsclient --create-frame

# Kill focused window
bindsym $mod+c kill

bindsym Mod1+Shift exec pkill -SIGRTMIN+10 i3blocks

# Start your launcher
bindsym $mod+p exec rolfi app-launcher

# Drag floating windows by holding down $mod and left mouse button.
# Resize them with right mouse button + $mod.
# Despite the name, also works for non-floating windows.
# Change normal to inverse to use left mouse button for resizing and right
# mouse button for dragging.

# Reload the configuration file
bindsym $mod+Shift+r reload
bindsym $mod+minus exec sh -c "amixer -q sset Master 3%- && pkill -SIGRTMIN+11 i3block"
bindsym $mod+equal exec sh -c "amixer -q sset Master 3%+ && pkill -SIGRTMIN+11 i3block"

# Exit sway (logs you out of your Wayland session)
bindsym $mod+Shift+q exec swaynag -t warning -m 'You pressed the exit shortcut. Do you really want to exit sway? This will end your Wayland session.' -B 'Yes, exit sway' 'swaymsg exit'
#+end_src

** Moving around:
#+begin_src sh

    # Move your focus around
    bindsym $mod+$left focus left
    bindsym $mod+$down focus down
    bindsym $mod+$up focus up
    bindsym $mod+$right focus right
    # Or use $mod+[up|down|left|right]
    bindsym $mod+Left focus left
    bindsym $mod+Down focus down
    bindsym $mod+Up focus up
    bindsym $mod+Right focus right

    # Move the focused window with the same, but add Shift
    bindsym $mod+Shift+$left move left
    bindsym $mod+Shift+$down move down
    bindsym $mod+Shift+$up move up
    bindsym $mod+Shift+$right move right
    # Ditto, with arrow keys
    bindsym $mod+Shift+Left move left
    bindsym $mod+Shift+Down move down
    bindsym $mod+Shift+Up move up
    bindsym $mod+Shift+Right move right
#+end_src

** Workspaces:
#+begin_src sh
    # Switch to workspace
    bindsym $mod+1 workspace number 1
    bindsym $mod+2 workspace number 2
    bindsym $mod+3 workspace number 3
    bindsym $mod+4 workspace number 4
    bindsym $mod+5 workspace number 5
    bindsym $mod+6 workspace number 6
    bindsym $mod+7 workspace number 7
    bindsym $mod+8 workspace number 8
    bindsym $mod+9 workspace number 9
    bindsym $mod+0 workspace number 10
    # Move focused container to workspace
    bindsym $mod+Shift+1 move container to workspace number 1
    bindsym $mod+Shift+2 move container to workspace number 2
    bindsym $mod+Shift+3 move container to workspace number 3
    bindsym $mod+Shift+4 move container to workspace number 4
    bindsym $mod+Shift+5 move container to workspace number 5
    bindsym $mod+Shift+6 move container to workspace number 6
    bindsym $mod+Shift+7 move container to workspace number 7
    bindsym $mod+Shift+8 move container to workspace number 8
    bindsym $mod+Shift+9 move container to workspace number 9
    bindsym $mod+Shift+0 move container to workspace number 10
    # Note: workspaces can have any name you want, not just numbers.
    # We just use 1-10 as the default.
#+end_src

** Layout stuff:
#+begin_src sh
# You can "split" the current object of your focus with
# $mod+b or $mod+v, for horizontal and vertical splits
# respectively.
bindsym $mod+b splith
bindsym $mod+v splitv

# Switch the current container between different layout styles
bindsym $mod+s layout stacking
bindsym $mod+w layout tabbed
#    bindsym $mod+e layout toggle split

# Make the current focus fullscreen
bindsym $mod+f fullscreen

# Toggle the current focus between tiling and floating mode
# Swap focus between the tiling area and the floating area
# bindsym $mod+space focus mode_toggle

# Move focus to the parent container
bindsym $mod+a focus parent

workspace_layout tabbed

#+end_src

** Scratchpad:
Sway has a "scratchpad", which is a bag of holding for windows.
You can send windows there and get them back later.
#+begin_src sh
    # Move the currently focused window to the scratchpad
    # bindsym $mod+Shift+down move scratchpad

    # Show the next scratchpad window or hide the focused scratchpad window.
    # If there are multiple scratchpad windows, this command cycles through them.
    # bindsym $mod+Shiftup scratchpad show
#+end_src

** Resizing containers:
   left will shrink the containers width
   right will grow the containers width
   up will shrink the containers height
   down will grow the containers height
#+begin_src sh

mode "resize" {
    bindsym $left resize shrink width 10px
    bindsym $down resize grow height 10px
    bindsym $up resize shrink height 10px
    bindsym $right resize grow width 10px

    # Ditto, with arrow keys
    bindsym Left resize shrink width 10px
    bindsym Down resize grow height 10px
    bindsym Up resize shrink height 10px
    bindsym Right resize grow width 10px

    # Return to default mode
    bindsym Return mode "default"
    bindsym Escape mode "default"
}
bindsym $mod+r mode "resize"
#+end_src

* I3blocks
#+begin_src emacs-lisp :tangle "../i3blocks/config"
[keylay]
command=sh -c "xkblayout-state print %s"
interval=once
signal=10

[net]
full_text="eduroam"
command=nmcli d wifi connect $(nmcli -t -f NAME,TIMESTAMP con  | sort -t: -nk2 | tail -n1 | cut -d: -f1) > /dev/null

[bat]
command=acpi | awk '{print $5}'
interval=30

[down_vol]
full_text="<|"
command=amixer -q sset Master 3%- && pkill -SIGRTMIN+11 i3blocks
color=#F79494

[volume]
command=/home/slamko/.config/i3/vol.sh
interval=once
signal=11

[up_vol]
full_text="|>"
command=amixer -q sset Master 3%+ && pkill -SIGRTMIN+11 i3blocks
color=#F79494

# Update time every 5 seconds
[time]
command=date "+%d/%m %R"
interval=10
#+end_src

* Status Bar:
** Basic config

 When the status_command prints a new line to stdout, swaybar updates.
 The default just shows the current date and time.
#+begin_src sh

bar {
 position top

    colors {
        statusline #ffffff
        background #323232
        inactive_workspace #32323200 #32323200 #5c5c5c
    }
  status_command i3blocks
}
#+end_src
** Variables
#+begin_src sh
default_border none
default_floating_border pixel
#+end_src

* System configs
#+begin_src sh
include /etc/sway/config.d/*
exec emacs --daemon --fullscreen
exec feh --bg-scale /home/slamko/.config/i3/bg.png
#+end_src
